package main

import "os"
import "fmt"
import "mapreduce"
import "strconv"
import "strings"
import "unicode"
import "sort"

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
// document 是文件的名字，value是文本的内容
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Your code here (Part V).
	f := func(c rune) bool {
		return !unicode.IsLetter(c) && !unicode.IsNumber(c)
	}
	keys := strings.FieldsFunc(value, f)
	
	for _, key := range keys{
		res = append(res, mapreduce.KeyValue{key, document})
	}
	return res
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Your code here (Part V).
	var uniqueValue []string
	sort.Strings(values)
	vis := make(map[string] bool)
	for _, value := range values{
		if(vis[value] == false){
			vis[value] = true
			uniqueValue = append(uniqueValue, value)
		}
	}
	length := len(vis)
	res := strconv.Itoa(length)+" "
	
	var fileList []string
	for k, _ := range vis{
		fileList = append(fileList, k)
	}
	sort.Strings(fileList)
	for index, value := range fileList{
		if index < length-1{
			res = res+value+","
		}else {
			res = res+value
		}
	}
	return res
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
